name: CI
on:
  push:
    branches:
      - main
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v4
          - name: Increment version
            id: increment-version
            uses: actions/github-script@v6
            with:
              script: |
                const currentVersion = 'v26'; 
                const currentVersionNumber = parseInt(currentVersion.substring(1));
                const nextVersionNumber = currentVersionNumber + 1;
                const nextVersion = 'v' + nextVersionNumber;
                core.setOutput('next-version', nextVersion);
          - name: output
            run: echo "The image is ${{ steps.increment-version.outputs.next-version }}"